### ISSUE TITLE
"Diamonds?" quest in the Stone Age cannot be completed until halfway through the Steam Age

### ISSUE THREAD

**Issue by ShadowDrakken** [MSandro/sky_fabrication2#10]
It's impossible to get Gold Ore until halfway through the Steam Age when the Steam Quarry gets built. None of the ore funnels up to Diamond level (not sure above that) produce Gold Ore, only Nether Gold Ore which doesn't count towards the quest.

**Comment by MSandro** [comment]
Hi, it is not easy, but not impossible. And it is optional.

**Comment by ShadowDrakken** [comment]
"Not impossible"? How do you get gold ore before you get a steam quarry?

**Comment by MSandro** [comment]
you habe to kill a lot of terrain slimes. They can drop any kind of vanilla ore. But it is a optional quest!
