### ISSUE TITLE
My game completely crashed after taking coal melon slices out of a barrel

### ISSUE THREAD

**Issue by Zazoot** [MSandro/sky_fabrication2#11]
My world that I've been working on for a few days cant even start up after after I tried to take coal melon out of a full item barrel hooked up to a plant jar on top and a hopper on the bottom. now every time i start the game up it crashes. godspeed masters of code

**Comment by MSandro** [comment]
You could try to remove the Stockpile mod. For some resons it cause crashes.
#7

**Comment by MSandro** [comment]
Maybe I will remove the mod in 1.0 because I can't fix the issue.

**Comment by Zazoot** [comment]
Thank you, once the stockpile mod was uninstalled everything ran smoothly

Sent from my Bell Samsung device over Canada’s largest network.
________________________________
