### ISSUE TITLE
interaction with any nearby blocks of sticky pistons in nether loot building causes server crash

### ISSUE THREAD

**Issue by kajdaniec** [MSandro/sky_fabrication2#12]
was exploring some nether then tried to open hidden room with levers and server crasher

**Comment by MSandro** [comment]
Please upload the crash report.

**Comment by kajdaniec** [comment]
Crash was only serverside

**Comment by MSandro** [comment]
Ok, I will check it tomorrow.

**Comment by MSandro** [comment]
i think this is the same as #14

**Comment by MSandro** [comment]
closed with #14
