### ISSUE TITLE
The iron funnel doesn't produce quartz

### ISSUE THREAD

**Issue by guest256** [MSandro/sky_fabrication2#2]
The questbook says its possible, but in the configs the quartz are places on gold funnel level.

**Comment by MSandro** [comment]
Thanks for reporting this. I think this is a wrong text in the quest book. Because I've changed some outputs. But ir seems that I've forgot to change some Quest Descriptions. You should be able to get Quartz now from the Gold Funnel.

**Comment by MSandro** [comment]
The wrong task and reward items are now changed in 0.8.2 to fit the output of the Iron Funnel.
