### ISSUE TITLE
Broken SCF Config

### ISSUE THREAD

**Issue by LeafyLuigi** [MSandro/sky_fabrication2#28]
In ..\config\SCF\ores.acfg, line 21 has `lightestlamp:monazite_ore` when it should most likely be `modern_industrialization:mozanite_ore`. Fixing this causes the Netherite Funnel to not have an "air" output chance (likely a fallback) and instead have, what's most likely, Mozanite.

**Comment by MSandro** [comment]
thank you, it will be fixed in the next update.

**Comment by MSandro** [comment]
will be solved in 1.0.6
