### ISSUE TITLE
Overwritten MI Aseembler Resistor Craft

### ISSUE THREAD

**Issue by LeafyLuigi** [MSandro/sky_fabrication2#30]
You can change the file name of this file: /kubejs/data/modern_industrialization/recipes/electric_age/component/assembler/resistor.json to allow the Tech Reborn Basic Machine Frame to be craftable in the assembler without overriding the resistor craft. It doesn't cause any errors in doing so.

**Comment by MSandro** [comment]
will be solved in 1.0.6
