### ISSUE TITLE
Game won't start "exception in thread main"

### ISSUE THREAD

**Issue by Berack96** [MSandro/sky_fabrication2#50]
OS: Windows11 version 21H2 (OSbuild 22000.613)
PC: AMD Ryzen 5 5600X - 32.0 GB (RAM) - ASUS TUF Nvidia 3070Ti
SW: Installation with Curseforge modpack "Sky FABRICation 2-1.1.2b.zip"

When starting the game with a fresh install of the modpack i get the following error (trying to copy the log will not expand the "... 3 more" or "... 6 more"):
![image](https://user-images.githubusercontent.com/31776951/167298745-9cd9a4ef-3923-4269-a27a-4bce447aacf0.png)

This might be correlated as well:
After re-starting the game, it start without the error but i'm unable to connect to servers:
![image](https://user-images.githubusercontent.com/31776951/167299096-6a0bc561-b4d7-4648-8865-b85250c40998.png)

Also "skyfabricator-1.0.6.jar" (that is the mod of the missing items) is seen as a trojan from Windows Defender.
![image](https://user-images.githubusercontent.com/31776951/167298625-295a9c78-a70d-4f73-bd45-f3323d64645a.png)

Restoring the mod in the folder, "whitelisting" it from Windows Defender and restarting the game will fix the issue.

**Comment by MSandro** [comment]
Thanks for reporting this, if you launch the modpack on the first time, you will get the error message which you posted above.
I'm sorry that this mod was flagged as a virus for you. I can't understand why.

It seems you were able to fix the problems, so I'll close this issue. If you still have problems, please open a new issue.
