### ISSUE TITLE
Unable to plant any seeds on Rich soil/farmland

### ISSUE THREAD

**Issue by Kellegram** [MSandro/sky_fabrication2#51]
By letting organic compost block decompose, Rich soil block is created. I then tilled it and it hydrated as expected, but I am unable to plant any seeds. At first I thought it just does not work with greenhouse glass so I waited for spring, but still couldn't plant anything. I replaced a rich soil block with dirt, tilled it and was able to plant and grow just fine.

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/167346403-6466bd30-f1fc-4fa2-97cd-344586e44525.png)
I was only able to grow tomatos on Rich Soil. 
However, this is a mod dependent issue, not directly related to this modpack or something I could fix.
