### ISSUE TITLE
"Quantum Circuit Board" not crafting

### ISSUE THREAD

**Issue by Luizfelz** [MSandro/sky_fabrication2#64]
Hi, guys.

I have this problem with my friends in our server (version 1.1.3 - release), when we try to craft a Quantum Circuit Board, but instead the "Assembler" machine crafts the Supraconductor Coil.
The image below shows the Quantum Circuit Board ingredients.
![image](https://i.imgur.com/2bgjkP8.png)

But, when I put the ingredients (regardless the position inside the Assembler), I recieve the Supraconductor Coil, instead, as shown below.  
![image](https://i.imgur.com/k9ZB5U0.png)

The Supraconductor Coil can be crafted in a normal workbench, but can also be crafted in the assembler, as shown below in both cases.
![image](https://i.imgur.com/X9VG8ug.png)
![image](https://i.imgur.com/842kS34.png)

I think the Assembler priorizes the craft of the Supraconductor Coil, not allowing us to craft the Quantum Circuit Board. We tried to put every other item BEFORE the 12 supraconductor cables, to see if the Assembler recognizes the Quantum Circuit Board pattern, but it consumes 8 supraconductor cables and craft the Supraconductor Coil no matter what we do...

Waiting for answers and help. Thanks  =D

Edit: I also tried to lock the crafting for the Quantum Circuit Board, but the Assembler NEVER starts the crafting, so it's impossible to lock the craft...

**Comment by MSandro** [comment]
Machine Upgrade was missing
