### ISSUE TITLE
Cash for air in inventory spot 0

### ISSUE THREAD

**Issue by mdinnocenzo** [MSandro/sky_fabrication2#7]
This seems to have happened a couple of times on the compressor.  Trying to open the device it crashes out.

[crash-2021-12-02_11.25.51-server.txt](https://github.com/MSandro/sky_fabrication2/files/7644279/crash-2021-12-02_11.25.51-server.txt)

**Comment by MSandro** [comment]
https://github.com/branchpanic/stockpile/issues/112
Sorry can not fix this a the time.

**Comment by mdinnocenzo** [comment]
Just trying to get these logged as I encounter them.  Thanks for the heads up, not a show stopper just a nuisance.

**Comment by MSandro** [comment]
Stockpile will be removed in v1.0!
