### ISSUE TITLE
CC UI Bug (missing textures)

### ISSUE THREAD

**Issue by AIMcgh** [MSandro/sky_fabrication2#70]
I don't know whether or not it's CC's code or a clash in your modpack, but the [UIs have no textures and become unusable](https://gyazo.com/7f70b72819a6921c1165c956b2efaa56).

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/180774050-33a019b4-7486-4052-b4b6-491312262ef0.png)
can not reproduce this issue in v1.1.3c
are u using a shader or a texturepack?

**Comment by AIMcgh** [comment]
I'm not, just suddenly happened, I used CC 1.1.3c before, for some reason this happened

**Comment by AIMcgh** [comment]
Ok, just tested it again and this time it works.
Maybe the mod didn't load properly before, bizarre.
