### ISSUE TITLE
gravel falling crashes and corrupts save

### ISSUE THREAD

**Issue by thallone** [MSandro/sky_fabrication2#71]
game crashes and corrupts save if a gravel falls on a lower slab. Sand too. to replicate start a new world in creative, remove the sapling, place 2 gravel or sand on the dirt, then a gravel or sand to the side where it will fall. Instant crash Tested sand as well, same result

I lost 3 survival worlds to inadvertent placements. 
 
[crash-2022-08-03_22.24.07-server.txt](https://github.com/MSandro/sky_fabrication2/files/9256421/crash-2022-08-03_22.24.07-server.txt)
.

**Comment by MSandro** [comment]
fixed since 0.4!

**Comment by MSandro** [comment]
and I know it was my mistake, I've inserted the wrong link to the button.
but this is the issue Tracker for SF2.
SF3 Issue Tracker: https://github.com/MSandro/sky_fabrication3/issues

**Comment by thallone** [comment]
Awesome, thanks. Apparently Curseforge didn't give notification of version update and I missed it. 

Great mod!
