### ISSUE TITLE
Game crash in the nether

### ISSUE THREAD

**Issue by JustinRG** [MSandro/sky_fabrication2#8]
When I entered the nether through the nether portal. The game crashed within seconds. Joining the (single player) world keeps crashing the game.

[crash-2021-12-03_15.59.52-server.txt](https://github.com/MSandro/sky_fabrication2/files/7650595/crash-2021-12-03_15.59.52-server.txt)

**Comment by MSandro** [comment]
Thanks I will check it.

**Comment by MSandro** [comment]
Could you try to update to 0.9.1? 
Or maybe try to delete/reset the nether dim-1 folder in your world?

**Comment by mdinnocenzo** [comment]
Getting the same experience on 0.9.1.  I have deleted the DIM-1 folder as well.  The first file is the crash report before deleting the DIM-1 folder, second is after.  This is after entering the nether for the first time, player is now stuck in the nether and the game will crash almost immediately.

[crash-2021-12-04_11.05.51-server.txt](https://github.com/MSandro/sky_fabrication2/files/7654407/crash-2021-12-04_11.05.51-server.txt)
[crash-2021-12-04_11.13.17-server.txt](https://github.com/MSandro/sky_fabrication2/files/7654408/crash-2021-12-04_11.13.17-server.txt)

**Comment by MSandro** [comment]
Thanks, I will try to find out what is causing the crash as soon as possible.

**Comment by MSandro** [comment]
fixed since 0.9.2
