### ISSUE TITLE
Cardinal Components Mixin exception

### ISSUE THREAD

**Issue by jkdoug** [MSandro/sky_fabrication2#9]
Installed the modpack (v0.9.2) through CurseForge app, and received this exception on first run:

> java.lang.RuntimeException: Error creating Mixin config mixins.cardinal_components_chunk.json for mod cardinal-components-chunk
>	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90)
>	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
>	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
>	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
>Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config mixins.cardinal_components_chunk.json
>	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
>	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
>	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
>	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88)
>	... 3 more
>Caused by: java.lang.IllegalArgumentException: The specified resource 'mixins.cardinal_components_chunk.json' was invalid or could not be read
>	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
>	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
>	... 6 more

**Comment by MSandro** [comment]
Hi, did you tried to re-install it?

**Comment by MSandro** [comment]
I can not reproduce this issue. Please let me know if re-installing the pack solved the issue.

**Comment by MSandro** [comment]
I was able to reproduce it.
